# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Custom Portal',
    'version': '1.0',
    'sequence': 1,
    'category': '',
    'website': '',
    'summary': '',
    'description': """  """,
    'depends': [
        'base', 'web',
        'mail', 'portal', 'project', 'hr_timesheet', 'hr_expense', 'planning','timesheet_grid'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/header_template.xml',
    ],

    'demo': [],

    'installable': True,
    'application': True,
    'assets': {
        # 'odoo_custom_portal.webclient': [
        #     ('include', 'web.assets_backend'),
        #     ('include', 'web._assets_bootstrap'),
        #     # ('remove', 'web/static/src/webclient/menus/*.js'),
        #
        #     # Remove Longpolling bus and packages needed this bus
        #     # ('remove', 'bus/static/src/js/services/assets_watchdog_service.js'),
        #     # ('remove', 'mail/static/src/services/messaging/messaging.js'),
        #
        #     # ('remove', 'mail/static/src/components/dialog_manager/dialog_manager.js'),
        #     # ('remove', 'mail/static/src/services/dialog_service/dialog_service.js'),
        #     # ('remove', 'mail/static/src/components/chat_window_manager/chat_window_manager.js'),
        #     # ('remove', 'mail/static/src/services/chat_window_service/chat_window_service.js'),
        #     'odoo_custom_portal/static/src/fonts/fonts.scss',
        #     'odoo_custom_portal/static/src/js/MainPortal/MainPortal.css',
        #     'odoo_custom_portal/static/src/js/DashBoard/DashBoard.scss',
        #     'odoo_custom_portal/static/src/js/Alerts/Alerts.css',
        #     'odoo_custom_portal/static/src/js/Downloads/Downloads.scss',
        #     'odoo_custom_portal/static/src/js/MyProfile/MyProfile.scss',
        #     'odoo_custom_portal/static/src/js/MyShifts/MyShifts.scss',
        #     'odoo_custom_portal/static/src/js/Newsletter/Newsletter.scss',
        #     'odoo_custom_portal/static/src/js/Requests/Requests.scss',
        #     'web/static/src/legacy/js/public/public_widget.js',
        #     # 'portal/static/src/js/portal_chatter.js',
        #     # 'portal/static/src/js/portal_composer.js',
        #     # 'project/static/src/project_sharing/search/favorite_menu/custom_favorite_item.xml',
        #     # 'project/static/src/project_sharing/**/*.js',
        #     # 'project/static/src/scss/project_sharing/*',
        #     'odoo_custom_portal/static/src/js/StartPortal/PortalClient.xml',
        #     'odoo_custom_portal/static/src/js/MainPortal/MainPortal.xml',
        #     'odoo_custom_portal/static/src/js/DashBoard/DashBoard.xml',
        #     'odoo_custom_portal/static/src/js/Alerts/Alerts.xml',
        #     'odoo_custom_portal/static/src/js/Downloads/Downloads.xml',
        #     'odoo_custom_portal/static/src/js/MyProfile/MyProfile.xml',
        #     'odoo_custom_portal/static/src/js/MyShifts/MyShifts.xml',
        #     'odoo_custom_portal/static/src/js/Newsletter/Newsletter.xml',
        #     'odoo_custom_portal/static/src/js/Requests/Requests.xml',
        #
        #     'odoo_custom_portal/static/src/js/StartPortal/startWebClient.js',
        #     'odoo_custom_portal/static/src/js/StartPortal/PortalClient.js',
        #     'odoo_custom_portal/static/src/js/MainPortal/MainPortal.js',
        #     'odoo_custom_portal/static/src/js/DashBoard/DashBoard.js',
        #     'odoo_custom_portal/static/src/js/Alerts/Alerts.js',
        #     'odoo_custom_portal/static/src/js/Downloads/Downloads.js',
        #     'odoo_custom_portal/static/src/js/MyProfile/MyProfile.js',
        #     'odoo_custom_portal/static/src/js/MyShifts/MyShifts.js',
        #     'odoo_custom_portal/static/src/js/Newsletter/Newsletter.js',
        #     'odoo_custom_portal/static/src/js/Requests/Requests.js',
        #     # 'odoo_custom_portal/static/src/js/home.js',
        #
        #     'web/static/src/start.js',
        #     'web/static/src/legacy/legacy_setup.js',
        #
        # ],
        #
        'odoo_custom_portal.webclient': [
            ('include', 'web._assets_helpers'),
            ('include', 'web._assets_backend_helpers'),

            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',

            ('include', 'web._assets_bootstrap'),

            'base/static/src/css/modules.css',

            'web/static/src/core/utils/transitions.scss',
            'web/static/src/core/**/*',
            'web/static/src/search/**/*',
            'web/static/src/webclient/icons.scss',  # variables required in list_controller.scss
            'web/static/src/views/*.js',
            'web/static/src/views/*.xml',
            'web/static/src/views/*.scss',
            'web/static/src/views/fields/**/*',
            ('remove', 'web/static/src/views/fields/journal_dashboard_graph/**/*'),
            # only works with graph view in assets
            'web/static/src/views/form/**/*',
            'web/static/src/views/kanban/**/*',
            'web/static/src/views/list/**/*',
            'web/static/src/views/view_button/**/*',
            'web/static/src/views/view_dialogs/**/*',
            'web/static/src/views/widgets/**/*',
            'web/static/src/webclient/**/*',
            ('remove', 'web/static/src/webclient/navbar/navbar.scss'),  # already in assets_common
            ('remove', 'web/static/src/webclient/clickbot/clickbot.js'),  # lazy loaded
            ('remove', 'web/static/src/views/form/button_box/*.scss'),

            # remove the report code and whitelist only what's needed
            ('remove', 'web/static/src/webclient/actions/reports/**/*'),
            'web/static/src/webclient/actions/reports/*.js',
            'web/static/src/webclient/actions/reports/*.xml',

            'web/static/src/env.js',

            'web/static/lib/jquery.scrollTo/jquery.scrollTo.js',
            'web/static/lib/py.js/lib/py.js',
            'web/static/lib/py.js/lib/py_extras.js',
            'web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js',

            'web/static/src/legacy/scss/fields.scss',
            'web/static/src/legacy/scss/views.scss',
            'web/static/src/legacy/scss/form_view.scss',
            'web/static/src/legacy/scss/list_view.scss',
            'web/static/src/legacy/scss/kanban_dashboard.scss',
            'web/static/src/legacy/scss/kanban_examples_dialog.scss',
            'web/static/src/legacy/scss/kanban_column_progressbar.scss',
            'web/static/src/legacy/scss/kanban_view.scss',

            'base/static/src/scss/res_partner.scss',

            # Form style should be computed before
            'web/static/src/views/form/button_box/*.scss',

            'web/static/src/legacy/action_adapters.js',
            'web/static/src/legacy/debug_manager.js',
            'web/static/src/legacy/legacy_service_provider.js',
            'web/static/src/legacy/legacy_client_actions.js',
            'web/static/src/legacy/legacy_dialog.js',
            'web/static/src/legacy/legacy_load_views.js',
            'web/static/src/legacy/legacy_promise_error_handler.js',
            'web/static/src/legacy/legacy_rpc_error_handler.js',
            'web/static/src/legacy/root_widget.js',
            'web/static/src/legacy/legacy_setup.js',
            'web/static/src/legacy/root_widget.js',
            'web/static/src/legacy/backend_utils.js',
            'web/static/src/legacy/utils.js',
            'web/static/src/legacy/web_client.js',
            'web/static/src/legacy/js/_deprecated/data.js',
            'web/static/src/legacy/js/chrome/*',
            'web/static/src/legacy/js/components/*',
            'web/static/src/legacy/js/control_panel/*',
            'web/static/src/legacy/js/core/domain.js',
            'web/static/src/legacy/js/core/mvc.js',
            'web/static/src/legacy/js/core/py_utils.js',
            'web/static/src/legacy/js/core/context.js',
            'web/static/src/legacy/js/core/misc.js',
            'web/static/src/legacy/js/fields/abstract_field.js',
            'web/static/src/legacy/js/fields/abstract_field_owl.js',
            'web/static/src/legacy/js/_deprecated/basic_fields.js',
            'web/static/src/legacy/js/fields/basic_fields.js',
            'web/static/src/legacy/js/fields/basic_fields_owl.js',
            'web/static/src/legacy/js/fields/field_utils.js',
            'web/static/src/legacy/js/fields/relational_fields.js',
            'web/static/src/legacy/js/fields/special_fields.js',
            'web/static/src/legacy/js/fields/field_registry.js',
            'web/static/src/legacy/js/fields/field_registry_owl.js',
            'web/static/src/legacy/js/fields/field_utils.js',
            'web/static/src/legacy/js/fields/field_wrapper.js',
            'web/static/src/legacy/js/views/sample_server.js',
            'web/static/src/legacy/js/views/abstract_model.js',
            'web/static/src/legacy/js/views/basic/basic_model.js',
            'web/static/src/legacy/js/views/action_model.js',
            'web/static/src/legacy/js/views/view_utils.js',
            'web/static/src/legacy/js/services/data_manager.js',
            'web/static/src/legacy/js/services/session.js',
            'web/static/src/legacy/js/tools/tools.js',
            'web/static/src/legacy/js/views/**/*',
            'web/static/src/legacy/js/widgets/data_export.js',
            'web/static/src/legacy/js/widgets/date_picker.js',
            'web/static/src/legacy/js/widgets/domain_selector_dialog.js',
            'web/static/src/legacy/js/widgets/domain_selector.js',
            'web/static/src/legacy/js/widgets/model_field_selector.js',
            'web/static/src/legacy/js/widgets/model_field_selector_popover.js',
            'web/static/src/legacy/js/env.js',
            'web/static/src/legacy/js/model.js',
            'web/static/src/legacy/js/owl_compatibility.js',

            'web_editor/static/src/components/**/*',
            'web_editor/static/src/scss/web_editor.common.scss',
            'web_editor/static/src/scss/web_editor.backend.scss',

            'web_editor/static/src/js/wysiwyg/dialog.js',
            'web_editor/static/src/js/frontend/loader.js',
            'web_editor/static/src/js/backend/**/*',
            'web_editor/static/src/xml/backend.xml',

            'mail/static/src/scss/variables/*.scss',
            'mail/static/src/widgets/**/*.scss',

            # 'project/static/src/components/project_task_name_with_subtask_count_char_field/*',
            # 'project/static/src/views/project_task_form/*.scss',
            #
            # 'project/static/src/project_sharing/search/favorite_menu/custom_favorite_item.xml',
            # 'project/static/src/project_sharing/**/*',
            'odoo_custom_portal/static/src/fonts/fonts.scss',
            'odoo_custom_portal/static/src/js/MainPortal/MainPortal.css',
            'odoo_custom_portal/static/src/js/DashBoard/DashBoard.scss',
            'odoo_custom_portal/static/src/js/Alerts/Alerts.css',
            'odoo_custom_portal/static/src/js/Downloads/Downloads.scss',
            'odoo_custom_portal/static/src/js/MyProfile/MyProfile.scss',
            'odoo_custom_portal/static/src/js/MyShifts/MyShifts.scss',
            'odoo_custom_portal/static/src/js/Newsletter/Newsletter.scss',
            'odoo_custom_portal/static/src/js/Requests/Requests.scss',
            'web/static/src/legacy/js/public/public_widget.js',
            # 'portal/static/src/js/portal_chatter.js',
            # 'portal/static/src/js/portal_composer.js',
            # 'project/static/src/project_sharing/search/favorite_menu/custom_favorite_item.xml',
            # 'project/static/src/project_sharing/**/*.js',
            # 'project/static/src/scss/project_sharing/*',
            'odoo_custom_portal/static/src/js/StartPortal/PortalClient.xml',
            'odoo_custom_portal/static/src/js/MainPortal/MainPortal.xml',
            'odoo_custom_portal/static/src/js/DashBoard/DashBoard.xml',
            'odoo_custom_portal/static/src/js/Alerts/Alerts.xml',
            'odoo_custom_portal/static/src/js/Downloads/Downloads.xml',
            'odoo_custom_portal/static/src/js/MyProfile/MyProfile.xml',
            'odoo_custom_portal/static/src/js/MyShifts/MyShifts.xml',
            'odoo_custom_portal/static/src/js/Newsletter/Newsletter.xml',
            'odoo_custom_portal/static/src/js/Requests/Requests.xml',

            'odoo_custom_portal/static/src/js/StartPortal/startWebClient.js',
            'odoo_custom_portal/static/src/js/StartPortal/PortalClient.js',
            'odoo_custom_portal/static/src/js/MainPortal/MainPortal.js',
            'odoo_custom_portal/static/src/js/DashBoard/DashBoard.js',
            'odoo_custom_portal/static/src/js/Alerts/Alerts.js',
            'odoo_custom_portal/static/src/js/Downloads/Downloads.js',
            'odoo_custom_portal/static/src/js/MyProfile/MyProfile.js',
            'odoo_custom_portal/static/src/js/MyShifts/MyShifts.js',
            'odoo_custom_portal/static/src/js/Newsletter/Newsletter.js',
            'odoo_custom_portal/static/src/js/Requests/Requests.js',
            'odoo_custom_portal/static/src/js/StartShiftView/start.js',
            # 'web/static/src/start.js',
            'web/static/src/legacy/legacy_setup.js',

        ],

        'odoo_custom_portal.shift_view_webclient': [
            ('include', 'web._assets_helpers'),
            ('include', 'web._assets_backend_helpers'),

            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',

            ('include', 'web._assets_bootstrap'),

            'base/static/src/css/modules.css',

            'web/static/src/core/utils/transitions.scss',
            'web/static/src/core/**/*',
            'web/static/src/search/**/*',
            'web/static/src/webclient/icons.scss',  # variables required in list_controller.scss
            'web/static/src/views/**/*',
            'web/static/src/webclient/**/*',
            ('remove', 'web/static/src/webclient/navbar/navbar.scss'),  # already in assets_common
            ('remove', 'web/static/src/webclient/clickbot/clickbot.js'),  # lazy loaded
            ('remove', 'web/static/src/views/form/button_box/*.scss'),

            # remove the report code and whitelist only what's needed
            ('remove', 'web/static/src/webclient/actions/reports/**/*'),
            'web/static/src/webclient/actions/reports/*.js',
            'web/static/src/webclient/actions/reports/*.xml',

            'web/static/src/env.js',

            'web/static/lib/jquery.scrollTo/jquery.scrollTo.js',
            'web/static/lib/py.js/lib/py.js',
            'web/static/lib/py.js/lib/py_extras.js',
            'web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js',

            'web/static/src/legacy/scss/domain_selector.scss',
            'web/static/src/legacy/scss/model_field_selector.scss',
            'web/static/src/legacy/scss/progress_bar.scss',
            'web/static/src/legacy/scss/dropdown.scss',
            'web/static/src/legacy/scss/tooltip.scss',
            'web/static/src/legacy/scss/switch_company_menu.scss',
            'web/static/src/legacy/scss/ace.scss',
            'web/static/src/legacy/scss/fields.scss',
            'web/static/src/legacy/scss/views.scss',
            'web/static/src/legacy/scss/form_view.scss',
            'web/static/src/legacy/scss/list_view.scss',
            'web/static/src/legacy/scss/kanban_dashboard.scss',
            'web/static/src/legacy/scss/kanban_examples_dialog.scss',
            'web/static/src/legacy/scss/kanban_column_progressbar.scss',
            'web/static/src/legacy/scss/kanban_view.scss',
            'web/static/src/legacy/scss/data_export.scss',
            'base/static/src/scss/onboarding.scss',
            'web/static/src/legacy/scss/attachment_preview.scss',
            'web/static/src/legacy/scss/base_document_layout.scss',
            'web/static/src/legacy/scss/special_fields.scss',
            'web/static/src/legacy/scss/fields_extra.scss',
            'web/static/src/legacy/scss/form_view_extra.scss',
            'web/static/src/legacy/scss/list_view_extra.scss',
            'web/static/src/legacy/scss/color_picker.scss',
            'base/static/src/scss/res_partner.scss',

            # Form style should be computed before
            'web/static/src/views/form/button_box/*.scss',

            'web/static/src/legacy/action_adapters.js',
            'web/static/src/legacy/debug_manager.js',
            'web/static/src/legacy/legacy_service_provider.js',
            'web/static/src/legacy/legacy_client_actions.js',
            'web/static/src/legacy/legacy_dialog.js',
            'web/static/src/legacy/legacy_load_views.js',
            'web/static/src/legacy/legacy_views.js',
            'web/static/src/legacy/legacy_promise_error_handler.js',
            'web/static/src/legacy/legacy_rpc_error_handler.js',
            'web/static/src/legacy/root_widget.js',
            'web/static/src/legacy/systray_menu.js',
            'web/static/src/legacy/systray_menu_item.js',
            'web/static/src/legacy/backend_utils.js',
            'web/static/src/legacy/utils.js',
            'web/static/src/legacy/web_client.js',
            'web/static/src/legacy/js/_deprecated/*',
            'web/static/src/legacy/js/chrome/*',
            'web/static/src/legacy/js/components/*',
            'web/static/src/legacy/js/control_panel/*',
            'web/static/src/legacy/js/core/domain.js',
            'web/static/src/legacy/js/core/mvc.js',
            'web/static/src/legacy/js/core/py_utils.js',
            'web/static/src/legacy/js/core/context.js',
            'web/static/src/legacy/js/core/misc.js',
            'web/static/src/legacy/js/fields/*',
            'web/static/src/legacy/js/services/data_manager.js',
            'web/static/src/legacy/js/services/session.js',
            'web/static/src/legacy/js/tools/tools.js',
            'web/static/src/legacy/js/views/**/*',
            'web/static/src/legacy/js/widgets/data_export.js',
            'web/static/src/legacy/js/widgets/date_picker.js',
            'web/static/src/legacy/js/widgets/domain_selector_dialog.js',
            'web/static/src/legacy/js/widgets/domain_selector.js',
            'web/static/src/legacy/js/widgets/iframe_widget.js',
            'web/static/src/legacy/js/widgets/model_field_selector.js',
            'web/static/src/legacy/js/widgets/model_field_selector_popover.js',
            'web/static/src/legacy/js/widgets/ribbon.js',
            'web/static/src/legacy/js/widgets/week_days.js',
            'web/static/src/legacy/js/widgets/signature.js',
            'web/static/src/legacy/js/widgets/attach_document.js',
            'web/static/src/legacy/js/apps.js',
            'web/static/src/legacy/js/env.js',
            'web/static/src/legacy/js/model.js',
            'web/static/src/legacy/js/owl_compatibility.js',

            'web/static/src/legacy/xml/base.xml',
            'web/static/src/legacy/xml/ribbon.xml',
            'web/static/src/legacy/xml/control_panel.xml',
            'web/static/src/legacy/xml/fields.xml',
            'web/static/src/legacy/xml/kanban.xml',
            'web/static/src/legacy/xml/search_panel.xml',
            'web/static/src/legacy/xml/week_days.xml',

            'web_enterprise/static/src/core/**/*',
            'web_enterprise/static/src/views/kanban/*',
            'web_enterprise/static/src/views/list/*',
            'web_enterprise/static/src/webclient/settings_form_view/*',
            'web_enterprise/static/src/webclient/navbar/*',
            'web_enterprise/static/src/webclient/promote_studio_dialog/*',
            'web_enterprise/static/src/webclient/webclient.js',

            'web_enterprise/static/src/legacy/js/core/*.js',
            'web_enterprise/static/src/legacy/js/views/*.js',
            'web_enterprise/static/src/legacy/js/widgets/*.js',

            'web_enterprise/static/src/legacy/scss/fields.scss',

            'web_gantt/static/src/**/*',
            'web_gantt/static/src/xml/**/*',

            'hr_gantt/static/src/js/**/*',
            'hr_gantt/static/src/xml/**/*',

            'hr/static/src/views/**/*.js',
            'hr/static/src/components/**/*',
            'hr/static/src/user_menu/*.js',
            'hr/static/src/scss/hr.scss',
            'hr/static/src/js/m2x_avatar_employee.js',
            'hr/static/src/js/standalone_m2o_avatar_employee.js',
            'hr/static/src/js/work_permit_upload.js',
            'hr/static/src/xml/*.xml',

            'planning/static/src/js/planning_mixins.js',
            'planning/static/src/js/planning_gantt_controller.js',
            'planning/static/src/js/planning_gantt_row.js',
            'planning/static/src/js/planning_gantt_utils.js',
            'planning/static/src/js/planning_gantt_renderer.js',
            'planning/static/src/js/planning_gantt_model.js',
            'planning/static/src/js/planning_gantt_view.js',
            'planning/static/src/js/widgets/*',
            'planning/static/src/views/**',
            'planning/static/src/scss/planning_gantt.scss',
            'planning/static/src/js/tours/planning.js',
            'planning/static/src/xml/**/*',
            'planning/static/src/views/**/*.js',
            'planning/static/src/views/**/*.xml',

            # depends on BS variables, can't be loaded in assets_primary or assets_secondary
            'mail/static/src/scss/variables/derived_variables.scss',
            # defines mixins and variables used by multiple components
            'mail/static/src/components/notification_list/notification_list_item.scss',
            'mail/static/src/js/**/*.js',
            'mail/static/src/utils/*.js',
            'mail/static/src/scss/*.scss',
            'mail/static/src/xml/*.xml',
            'mail/static/src/component_hooks/*.js',
            'mail/static/src/backend_components/*/*',
            'mail/static/src/components/*/*.js',
            'mail/static/src/components/*/*.scss',
            'mail/static/src/components/*/*.xml',
            'mail/static/src/views/*/*.xml',
            ('include', 'mail.assets_messaging'),
            'mail/static/src/services/*.js',
            'mail/static/src/views/**/*.js',
            'mail/static/src/views/**/*.xml',
            'mail/static/src/views/**/*.scss',
            'mail/static/src/webclient/commands/*.js',
            'mail/static/src/widgets/*/*.js',
            'mail/static/src/widgets/*/*.scss',

            # Don't include dark mode files in light mode
            ('remove', 'mail/static/src/components/*/*.dark.scss'),


            'odoo_custom_portal/static/src/js/StartShiftView/PortalShiftView.xml',
            'odoo_custom_portal/static/src/js/StartShiftView/ControlPanelShiftView.xml',
            #
            'odoo_custom_portal/static/src/fonts/fonts.scss',
            'odoo_custom_portal/static/src/js/StartShiftView/PortalShiftView.js',
            'odoo_custom_portal/static/src/js/StartShiftView/ShiftViewControlPanel.js',
            'odoo_custom_portal/static/src/js/StartShiftView/ControlPanelShiftView.js',
            'odoo_custom_portal/static/src/js/StartShiftView/startWebClient.js',
            # 'web/static/src/start.js',
            'odoo_custom_portal/static/src/js/StartShiftView/start.js',
            'web/static/src/legacy/legacy_setup.js',

        ],


    },
    'license': 'LGPL-3',
}
